### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by TomerGamerTV** [whiterabb17/strongarm#1]
I'm getting this error:

On on windows
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/whiterabb17/strongarm/library.startTaskService()
        D:/Local Downloads/strongarm/library/strongarm.go:187 +0xa7d
github.com/whiterabb17/strongarm/library.BeginBrute({0xc00001e130?, 0xc00005e000?}, {0xc00001e170?, 0xa565d9?}, 0x60?, 0x0?, {0xc00001e190?, 0x0?}, {0xc00001e1c0, 0xe}, ...)
        D:/Local Downloads/strongarm/library/strongarm.go:61 +0x10e
main.main()
        D:/Local Downloads/strongarm/standalone/main.go:42 +0x1b0
exit status 2

```

**Comment by whiterabb17** [comment]
you didnt supply it with either a list of targets of user/pass combos to try

**Comment by TomerGamerTV** [comment]
I did i copy pasted the example you gave and changed stuff

**Comment by whiterabb17** [comment]
What protocol were you trying to use

**Comment by whiterabb17** [comment]
You are also trying to use the library, instead of the standalone build

**Comment by whiterabb17** [comment]
Please pull the latest update.
The issue has been solved

**Comment by TomerGamerTV** [comment]
it seems like it's working is the program supposed to keep printing a lot of lines?

**Comment by whiterabb17** [comment]
yes, if it doesnt crash it works. Will just end with an empty "Success:" line if no results are found
